# Author Natraj Solai
# Updating the client feed data file from /home/linuxraja/data  to Client ftp server 
# After uploading, moving the file to /home/linuxraja/data  /backup

cd /home/linuxraja/data 
if [ `ls -ltr|wc -l` -gt 2 ]; then
echo "file exits"
else
echo "No file"
mailx -r user1@domain.com -s "Data Feed Failure - No files Generated by Database Server" "user2@domain.com" < /home/linuxraja/nofile.txt
exit ;
fi

ftp -n -i 0.0.0.0 << EOF
user user1 password
bin
lcd /home/linuxraja/data
mput *.zip
bye
EOF

count=$?
echo $count
if [ $count -lt 1 ]; then
mailx -r nagios@domain.com -s "Data Feed Sucessful" "user2@domain.com" < /home/linuxraja/success.txt
echo "Feed Sucessful ${DATE}"
else
mailx -r nagios@gadmst-minver.com -s "Data Feed  Fails - Client FTP error" "user2@domain.com" < /home/linuxraja/fail.txt
fi

mv *.zip backup/.
