# Author Natraj Solai
# Client Feed data Uploading - SFTP
cd /home/linuxraja/data
if [ `ls -ltr|wc -l` -gt 2 ]; then
echo "file exits"
else
echo "No file"
mailx -r nagios@domain.com -s "Client Feed Failure - No files Generated by Database Server" "user1@domain.com" < /home/linuxraja/nofile.txt
exit ;
fi

./ss1.sh

count=$?
echo $count
if [ $count -lt 1 ]; then
echo "Feed Sucessful ${DATE}"
else
  mailx -r nagios@domain.com -s "Client Feed Fails - Client FTP error" "user1@domain.com" < /home/linuxraja/fail.txt
fi

mv *.zip backup/.

**************
bash-2.03$ cat ss1.sh
#!/usr/local/bin/expect
spawn /usr/local/bin/sftp user@0.0.0.0
expect "password:"
send "password\n"
expect "sftp> "
send "mput *.zip\n"
expect "sftp> "
send "quit\n"
